catalog/urls.py
from django.urls import path, include
from catalog import views

from .views import (
    UserListView,
    UserDetailView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    CityListView,
    CityDetailView,
    CityCreateView,
    CityUpdateView,
    CityDeleteView,
    ReviewListView,
    ReviewDetailView,
    ReviewCreateView,
    ReviewUpdateView,
    ReviewDeleteView,
    RouteListView,
    RouteDetailView,
    RouteCreateView,
    RouteUpdateView,
    RouteDeleteView,
)


urlpatterns = [
    path("", views.index, name="index"),
    path("users", UserListView.as_view(), name="user-list"),
    path("user/<int:pk>/", UserDetailView.as_view(), name="user-detail"),
    path("user/create/", UserCreateView.as_view(), name="user-create"),
    path(
        "user/<int:pk>/delete/",
        UserDeleteView.as_view(),
        name="user-delete"
    ),
    path(
        "user/<int:pk>/update/",
        UserUpdateView.as_view(),
        name="user-update"
    ),
    path("cities/", CityListView.as_view(), name="city-list"),
    path("city/<int:pk>/", CityDetailView.as_view(), name="city-detail"),
    path(
        "city/create/",
        CityCreateView.as_view(),
        name="city-create"
    ),
    path(
        "city/<int:pk>/update/",
        CityUpdateView.as_view(),
        name="city-update"
    ),
    path(
        "city/<int:pk>/delete/",
        CityDeleteView.as_view(),
        name="city-delete"
    ),
    path("reviews/", ReviewListView.as_view(), name="review-list"),
    path(
        "review/<int:pk>/",
        ReviewDetailView.as_view(),
        name="review-detail"
    ),
    path(
        "review/create/",
        ReviewCreateView.as_view(),
        name="review-create"
    ),
    path(
        "review/<int:pk>/update/",
        ReviewUpdateView.as_view(),
        name="review-update"
    ),
    path(
        "review/<int:pk>/delete/",
        ReviewDeleteView.as_view(),
        name="review-delete"
    ),
    path("routes/", RouteListView.as_view(), name="route-list"),
    path("route/<int:pk>/", RouteDetailView.as_view(), name="route-detail"),
    path(
        "route/create/",
        RouteCreateView.as_view(),
        name="route-create"
    ),
    path(
        "route/<int:pk>/update/",
        RouteUpdateView.as_view(),
        name="route-update"
    ),
    path(
        "route/<int:pk>/delete/",
        RouteDeleteView.as_view(),
        name="route-delete"
    )
]

app_name = "catalog"

travel_guide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls"), name="catalog",),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "travel_guide"

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-gradient-dark z-index-3 py-3 position-fixed start-0 end-0 top-0">
  <div class="container">
    <a class="navbar-brand text-white" href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom" target="_blank">
      Home
    </a>
    {% if user.is_authenticated %}
      <a href="{% url 'logout' %}" class="btn btn-sm bg-gradient-danger btn-round mb-0 ms-auto d-lg-none d-block">Logout</a>
    {% else %}
      <a href="{% url 'login' %}" class="btn btn-sm bg-gradient-success btn-round mb-0 ms-auto d-lg-none d-block">Login</a>
    {% endif %}
    <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon mt-2">
        <span class="navbar-toggler-bar bar1"></span>
        <span class="navbar-toggler-bar bar2"></span>
        <span class="navbar-toggler-bar bar3"></span>
      </span>
    </button>
    <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0" id="navigation">
      <ul class="navbar-nav navbar-nav-hover mx-auto">
        <li class="nav-item mx-2">
          <a class="nav-link" href="{% url 'catalog:user-list' %}">Users</a>
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link" href="{% url 'catalog:city-list' %}">Cities</a>
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link" href="{% url 'catalog:review-list' %}">Reviews</a>
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link" href="{% url 'catalog:route-list' %}">Routes</a>
        </li>
        {% if user.is_authenticated %}
          {% with current_user=request.user.username %}
            <li>
              <a class="nav-link" href="{% url 'catalog:user-detail' user.id %}">User: {{ current_user }}</a>
            </li>
          {% endwith %}
        {% endif %}

      </ul>
      <ul class="navbar-nav d-lg-block d-none">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'logout' %}" class="btn btn-sm bg-gradient-danger mb-0 me-1" role="button">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'login' %}" class="btn btn-sm bg-gradient-success mb-0 me-1" role="button">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
<section class="container py-5 w-100">
  <ul class="pagination pagination-lg pagination-primary m-4 d-flex justify-content-center gap-3">
    <li class="page-item">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
        </li>
      {% endif %}
      <li class="page-item active">
        <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
        </li>
      {% endif %}
  </ul>
</section>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li>
      <a href="{% url 'catalog:user-detail' user.id %}">User: {{ user.username }}</a>
    </li>
    <li>
      <a href="{% url 'catalog:logout' %}">Logout</a>
  {% else %}
    <li>
      <a href="{% url 'catalog:login' %}">Login</a>
    </li>
  {% endif %}
  <li><a href="{% url 'catalog:index' %}">Home page</a></li>
  <li><a href="{% url 'catalog:user-list' %}">Users</a></li>
  <li><a href="{% url 'catalog:city-list' %}">Cities</a></li>
  <li><a href="{% url 'catalog:review-list' %}">Reviews</a></li>
  <li><a href="{% url 'catalog:route-list' %}">Routes</a></li>
</ul>