catalog/urls.py
from django.urls import path, include
from catalog import views

from .views import (
    UserListView,
    UserDetailView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    CityListView,
    CityDetailView,
    CityCreateView,
    CityUpdateView,
    CityDeleteView,
    ReviewListView,
    ReviewDetailView,
    ReviewCreateView,
    ReviewUpdateView,
    ReviewDeleteView,
    RouteListView,
    RouteDetailView,
    RouteCreateView,
    RouteUpdateView,
    RouteDeleteView,
)


urlpatterns = [
    path("", views.index, name="index"),
    path("users", UserListView.as_view(), name="user-list"),
    path("user/<int:pk>/", UserDetailView.as_view(), name="user-detail"),
    path("user/create/", UserCreateView.as_view(), name="user-create"),
    path(
        "user/<int:pk>/delete/",
        UserDeleteView.as_view(),
        name="user-delete"
    ),
    path(
        "user/<int:pk>/update/",
        UserUpdateView.as_view(),
        name="user-update"
    ),
    path("cities/", CityListView.as_view(), name="city-list"),
    path("city/<int:pk>/", CityDetailView.as_view(), name="city-detail"),
    path(
        "city/create/",
        CityCreateView.as_view(),
        name="city-create"
    ),
    path(
        "city/<int:pk>/update/",
        CityUpdateView.as_view(),
        name="city-update"
    ),
    path(
        "city/<int:pk>/delete/",
        CityDeleteView.as_view(),
        name="city-delete"
    ),
    path("reviews/", ReviewListView.as_view(), name="review-list"),
    path(
        "review/<int:pk>/",
        ReviewDetailView.as_view(),
        name="review-detail"
    ),
    path(
        "review/create/",
        ReviewCreateView.as_view(),
        name="review-create"
    ),
    path(
        "review/<int:pk>/update/",
        ReviewUpdateView.as_view(),
        name="review-update"
    ),
    path(
        "review/<int:pk>/delete/",
        ReviewDeleteView.as_view(),
        name="review-delete"
    ),
    path("routes/", RouteListView.as_view(), name="route-list"),
    path("route/<int:pk>/", RouteDetailView.as_view(), name="route-detail"),
    path(
        "route/create/",
        RouteCreateView.as_view(),
        name="route-create"
    ),
    path(
        "route/<int:pk>/update/",
        RouteUpdateView.as_view(),
        name="route-update"
    ),
    path(
        "route/<int:pk>/delete/",
        RouteDeleteView.as_view(),
        name="route-delete"
    )
]

app_name = "catalog"

travel_guide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls"), name="catalog",),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "travel_guide"

catalog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def __str__(self) -> str:
        return self.username


class City(models.Model):
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    population = models.IntegerField()
    attractions = models.TextField()

    def __str__(self) -> str:
        return self.name


class Review(models.Model):
    rating = models.IntegerField()
    comment = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reviews")
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name="reviews")

    def __str__(self) -> str:
        return f"{self.rating} - {self.comment}"


class Route(models.Model):
    name = models.CharField(max_length=255)
    duration = models.DurationField()
    budget = models.DecimalField(max_digits=10, decimal_places=2)
    points_of_interest = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="routes")

    def __str__(self) -> str:
        return self.name

catalog/forms.py
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from django import forms

from catalog.models import User


class UserCreationForm(BaseUserCreationForm):
    class Meta:
        model = User
        fields = BaseUserCreationForm.Meta.fields + (
            "username",
            "email",
            "first_name",
            "last_name"
        )


class UserSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class CitySearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class RouteSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )

catalog/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpRequest, HttpResponse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from catalog.models import User, City, Review, Route
from catalog.forms import (
    UserCreationForm,
    UserSearchForm,
    CitySearchForm,
    RouteSearchForm
)


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_users = User.objects.count()
    num_cities = City.objects.count()
    num_reviews = Review.objects.count()
    num_routes = Route.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_users": num_users,
        "num_cities": num_cities,
        "num_reviews": num_reviews,
        "num_routes": num_routes,
        "num_visits": num_visits + 1
    }
    return render(request, "catalog/index.html", context=context)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "user_list.html"
    context_object_name = "users"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = UserSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = User.objects.all()
        form = UserSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "catalog/user_detail.html"
    context_object_name = "user"


class UserCreateView(LoginRequiredMixin, CreateView):
    model = User
    success_url = reverse_lazy("catalog:user-list")
    form_class = UserCreationForm


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = "__all__"
    success_url = reverse_lazy("catalog:user-list")
    template_name = "catalog/user_form.html"


class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy("catalog:user-list")


class CityListView(ListView):
    model = City
    template_name = "city_list.html"
    context_object_name = "cities"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CityListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = CitySearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = City.objects.all()
        form = CitySearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class CityDetailView(LoginRequiredMixin, DetailView):
    model = City
    template_name = "catalog/city_detail.html"
    context_object_name = "city"


class CityCreateView(LoginRequiredMixin, CreateView):
    model = City
    fields = "__all__"
    success_url = reverse_lazy("catalog:city-list")
    template_name = "catalog/city_form.html"


class CityUpdateView(LoginRequiredMixin, UpdateView):
    model = City
    fields = "__all__"
    success_url = reverse_lazy("catalog:city-list")
    template_name = "catalog/city_form.html"


class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = City
    fields = "__all__"
    success_url = reverse_lazy("catalog:city-list")
    template_name = "catalog/city_confirm_delete.html"


class ReviewListView(LoginRequiredMixin, ListView):
    model = Review
    template_name = "review_list.html"
    context_object_name = "reviews"
    paginate_by = 5


class ReviewDetailView(LoginRequiredMixin, DetailView):
    model = Review
    template_name = "catalog/review_detail.html"
    context_object_name = "review"


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    fields = "__all__"
    success_url = reverse_lazy("catalog:review-list")
    template_name = "catalog/review_form.html"


class ReviewUpdateView(LoginRequiredMixin, UpdateView):
    model = Review
    fields = "__all__"
    success_url = reverse_lazy("catalog:review-list")
    template_name = "catalog/review_form.html"


class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    model = Review
    fields = "__all__"
    success_url = reverse_lazy("catalog:review-list")
    template_name = "catalog/review_confirm_delete.html"


class RouteListView(LoginRequiredMixin, ListView):
    model = Route
    template_name = "route_list.html"
    context_object_name = "routes"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RouteListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = RouteSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Route.objects.all()
        form = RouteSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class RouteDetailView(LoginRequiredMixin, DetailView):
    model = Route
    template_name = "catalog/route_detail.html"
    context_object_name = "route"


class RouteCreateView(LoginRequiredMixin, CreateView):
    model = Route
    fields = "__all__"
    success_url = reverse_lazy("catalog:route-list")
    template_name = "catalog/route_form.html"


class RouteUpdateView(LoginRequiredMixin, UpdateView):
    model = Route
    fields = "__all__"
    success_url = reverse_lazy("catalog:route-list")
    template_name = "catalog/route_form.html"


class RouteDeleteView(LoginRequiredMixin, DeleteView):
    model = Route
    fields = "__all__"
    success_url = reverse_lazy("catalog:route-list")
    template_name = "catalog/route_confirm_delete.html"

templates/catalog/city_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1520769945061-0a448c463865?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80');" loading="lazy">
    <span class="mask bg-gradient-dark opacity-5"></span>
      <div class="container d-flex justify-content-center">
        <div>
          <h1 class="text-white mb-4">Delete City</h1>
          <p class="text-white opacity-8 lead pe-5 me-5">Are you sure you want to delete the city: <br/> {{ city }}? </p>
          <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Yes, delete" class="btn btn-danger" />
            <a href="{% url 'catalog:city-list' %}" class="btn btn-secondary ms-3">Cancel</a>
          </form>
        </div>
      </div>
  </div>
{% endblock %}

templates/catalog/city_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header flex-column align-items-start pt-8 min-vh-100"
       style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80');"
       loading="lazy">
    <div class="container-fluid d-flex justify-content-center" style="margin-top: 20px">
      <div class="card">
        <h1 class="mb-4 mt-4 container-fluid d-flex justify-content-center">City list<a href="{% url 'catalog:city-create' %}" class="btn btn-primary link-to-page ml-4 mt-1">Create</a></h1>
        <p class="container-fluid d-flex justify-content-center lead px-5">On the page you will find a list <br> of all cities available in the application. <br> Here you can familiarize yourself with all <br> the cities that are registered in the <br> system, as well as view their main details. <br> This page allows you to conveniently view <br> and manage the list of cities in your application.
        {% if cities %}

          <form method="get" action="" class="form-inline mb-4 container-fluid d-flex justify-content-center">
            {{ search_form|crispy }}
            <input class="btn bg-gradient-light w-auto m-0" type="submit" value="Search">
          </form>
          <div style="margin-left:100px">
            <ul>
              {% for city in cities %}
                <li class="container d-flex">
                  <strong>ID:</strong> <a href="{% url 'catalog:city-detail' pk=city.pk %}">
                  {{ city.id }} - {{ city.name }}
                </a>
                </li>
              {% endfor %}
            </ul>
          </div>
        {% else %}
          <p>There are no cities in the catalog</p>
        {% endif %}
      </div>
    </div>
    {% include "includes/pagination.html" %}
  </div>
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}
{% load static %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

<header class="header-2">
  <div class="page-header min-vh-75 relative" style="background-image: url('{% static 'img/bg2.jpg' %}')">
    <span class="mask bg-gradient-primary opacity-4"></span>
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">Travel Guide</h1>
          <p class="lead text-white mt-3">
            Welcome
            <br/>
            The page contains articles, tips and useful travel information to help users prepare for their travels. 
            <br/>
            You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
          </p>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">

<section class="pt-3 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 mx-auto py-3">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary">{{ num_cities }}</h1>
              <h5 class="mt-3">Cities</h5>
              <p class="text-sm font-weight-normal">Find out more about: country, population, coordinates and attractions</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary">{{ num_reviews }}</h1>
              <h5 class="mt-3">Reviews</h5>
              <p class="text-sm font-weight-normal">Find out more about: rating, comments, authors and cities</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary">{{ num_routes }}</h1>
              <h5 class="mt-3">Routes</h5>
              <p class="text-sm font-weight-normal">Find out more about: duration, budget, points of interest and authors</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div>
{% endblock content %}

templates/catalog/review_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1520769945061-0a448c463865?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80');" loading="lazy">
    <span class="mask bg-gradient-dark opacity-5"></span>
      <div class="container d-flex justify-content-center">
        <div>
          <h1 class="text-white mb-4">Delete Review</h1>
          <p class="text-white opacity-8 lead pe-5 me-5">Are you sure you want to delete the review: <br/> {{ review }}? </p>
          <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Yes, delete" class="btn btn-danger" />
            <a href="{% url 'catalog:city-list' %}" class="btn btn-secondary ms-3">Cancel</a>
          </form>
        </div>
      </div>
  </div>
{% endblock %}

templates/catalog/review_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header flex-column align-items-start pt-8 min-vh-100"
       style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80');"
       loading="lazy">
    <div class="container-fluid d-flex justify-content-center" style="margin-top: 20px">
      <div class="card p-4">
        <h1 class="mb-4 mt-4 container-fluid d-flex justify-content-center">Review Detail</h1>

        <ul class="px-4">
          <li><strong>ID:</strong> {{ review.id }}</li>
          <li><strong>Rating:</strong> {{ review.rating }}</li>
          <li><strong>Comment:</strong> {{ review.comment }}</li>
          <li><strong>Author:</strong> {{ review.author.username }}</li>
          <li><strong>City:</strong> {{ review.city.name }}</li>
          <div class="d-flex justify-content-center align-items-center mt-5">
          <span>
            <a href="{% url 'catalog:review-update' pk=review.id %}" class="btn bg-gradient-warning me-2">UPDATE</a>
            <a href="{% url 'catalog:review-delete' pk=review.id %}" class="btn bg-gradient-danger">DELETE</a>
          </span>
          </div>
        </ul>
      </div>
    </div>
    {% include "includes/pagination.html" %}
  </div>
{% endblock %}

templates/catalog/review_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="page-header flex-column align-items-start pt-8 min-vh-100"
       style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80');"
       loading="lazy">
    <div class="container-fluid d-flex justify-content-center" style="margin-top: 20px">
      <div class="card p-4">
        <section>
          <div class="container py-4">
            <div class="row">
              <div class="col-lg-10 mx-auto d-flex justify-content-center flex-column">
                <h3 class="text-center">{{ object|yesno:"Update, Create" }} Review</h3>
                <form action="" method="post" novalidate class="text-center lead">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <input class="btn bg-gradient-dark w-50" type="submit" value="Submit">
                </form>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/review_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header flex-column align-items-start pt-8 min-vh-100"
       style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80');"
       loading="lazy">
    <div class="container-fluid d-flex justify-content-center" style="margin-top: 20px">
      <div class="card">
        <h1 class="mb-4 mt-4 container-fluid d-flex justify-content-center">Review list<a href="{% url 'catalog:review-create' %}" class="btn btn-primary link-to-page ml-4 mt-1">Create</a></h1>
        <p class="container-fluid d-flex justify-content-center lead px-5">On the page, you can view all the user reviews of <br>the various reviews that are available in the app. <br>Here you can read the impressions and opinions <br>of users about various aspects of the facilities <br>and their maintenance. This page gives you the <br>opportunity to get information about the opinions and <br>impressions of other users before making your choice.</p>
        {% if reviews %}


          <div style="margin-left:150px">
            <ul>
              {% for review in reviews %}
                <li class="container d-flex">
                  <strong>ID:</strong> <a href="{% url 'catalog:review-detail' pk=review.pk %}">
                  {{ review.id }} - {{ review.author.username }}
                </a>
                </li>
              {% endfor %}
            </ul>
          </div>
        {% else %}
          <p>There are no reviews in the catalog</p>
        {% endif %}
      </div>
    </div>
    {% include "includes/pagination.html" %}
  </div>
{% endblock %}

templates/catalog/route_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header flex-column align-items-start pt-8 min-vh-100"
       style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80');"
       loading="lazy">
    <div class="container-fluid d-flex justify-content-center" style="margin-top: 20px">
      <div class="card p-4">
        <h1 class="mb-4 mt-4 container-fluid d-flex justify-content-center">Route Detail</h1>

        <ul class="px-4">
          <li><strong>ID:</strong> {{ route.id }}</li>
          <li><strong>Name:</strong> {{ route.name }}</li>
          <li><strong>Duration:</strong> {{ route.duration }}</li>
          <li><strong>Budget:</strong> {{ route.budget }}</li>
          <li><strong>Points of Interest:</strong> {{ route.points_of_interest }}</li>
          <li><strong>Author:</strong> {{ route.author.username }}</li>
          <div class="d-flex justify-content-center align-items-center mt-5">
          <span>
            <a href="{% url 'catalog:route-update' pk=route.id %}" class="btn bg-gradient-warning me-2">UPDATE</a>
            <a href="{% url 'catalog:route-delete' pk=route.id %}" class="btn bg-gradient-danger">DELETE</a>
          </span>
          </div>
        </ul>
      </div>
    </div>
    {% include "includes/pagination.html" %}
  </div>
{% endblock %}

templates/catalog/route_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header flex-column align-items-start pt-8 min-vh-100"
       style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80');"
       loading="lazy">
    <div class="container-fluid d-flex justify-content-center" style="margin-top: 20px">
      <div class="card">
        <h1 class="mb-4 mt-4 container-fluid d-flex justify-content-center">Route list<a href="{% url 'catalog:route-create' %}" class="btn btn-primary link-to-page ml-4 mt-1">Create</a></h1>
        <p class="container-fluid d-flex justify-content-center lead px-5">On the page you will find a list of available routes <br>for travel and excursions. There are a variety <br>of itineraries that can be chosen for trips <br>of different types and durations. You will <br>be able to learn about the main attractions <br>that are included in each itinerary.</p>
        {% if routes %}

          <form method="get" action="" class="form-inline mb-4 container-fluid d-flex justify-content-center">
            {{ search_form|crispy }}
            <input class="btn bg-gradient-light w-auto m-0" type="submit" value="Search">
          </form>
          <div style="margin-left:100px">
            <ul>
              {% for route in routes %}
                <li class="container d-flex">
                  <strong>ID:</strong> <a href="{% url 'catalog:route-detail' pk=route.pk %}">
                  {{ route.id }} - {{ route.name }}
                </a>
                </li>
              {% endfor %}
            </ul>
          </div>
        {% else %}
          <p>There are no routes in the catalog</p>
        {% endif %}
      </div>
    </div>
    {% include "includes/pagination.html" %}
  </div>
{% endblock %}

templates/catalog/user_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header flex-column align-items-start pt-8 min-vh-100"
       style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80');"
       loading="lazy">
    <div class="container-fluid d-flex justify-content-center" style="margin-top: 20px">
      <div class="card p-4">
        <h1 class="mb-4 mt-4 container-fluid d-flex justify-content-center">User Detail</h1>

        <ul class="px-4">
          <li><strong>ID:</strong> {{ user.id }}</li>
          <li><strong>Username:</strong> {{ user.username }}</li>
          <li><strong>Email:</strong> {{ user.email }}</li>
          <li><strong>First Name:</strong> {{ user.first_name }}</li>
          <li><strong>Last Name:</strong> {{ user.last_name }}</li>
        </ul>
        {% if user.pk == request.user.pk %}
          <div class="text-center">
            <a href="{% url 'catalog:user-update' pk=user.pk %}" class="btn bg-gradient-warning me-2"
               style="width: fit-content;">UPDATE</a>
          </div>
        {% endif %}
      </div>
    </div>
    {% include "includes/pagination.html" %}
  </div>
{% endblock %}

templates/catalog/user_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header flex-column align-items-start pt-8 min-vh-100"
       style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80');"
       loading="lazy">
    <div class="container-fluid d-flex justify-content-center" style="margin-top: 20px">
      <div class="card">
        <h1 class="mb-4 mt-4 container-fluid d-flex justify-content-center">User list</h1>
        <p class="container-fluid d-flex justify-content-center lead px-5">User List is a page that displays the
          list <br> of users of the application. On this page, <br> you can view all the users who are <br> registered
          in the system along with their <br> basic details such as ID, username, and <br> email.</p>
        {% if users %}

          <form method="get" action="" class="form-inline mb-4 container-fluid d-flex justify-content-center">
            {{ search_form|crispy }}
            <input class="btn bg-gradient-light w-auto m-0" type="submit" value="Search">
          </form>
          <div style="margin-left:100px">
            <ul>
              {% for user in users %}
                <li class="container d-flex">
                  <strong>ID:</strong> <a href="{% url 'catalog:user-detail' pk=user.pk %}">
                  {{ user.id }} - {{ user.username }}
                </a>
                </li>
              {% endfor %}
            </ul>
          </div>
        {% else %}
          <p>There are no users in the catalog</p>
        {% endif %}
      </div>
    </div>
    {% include "includes/pagination.html" %}
  </div>
{% endblock %}